version: "3.9"
services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse_proxy
    depends_on:
        - frontend
        - backend
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "8000:80"
    restart: on-failure
  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend/build/docker/
    ports:
      - 8080:8080
    restart: on-failure