version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
  backend:
    build: ./backend/build/docker/
    ports:
      - "8080:8080"